// Generated by Selenium IDE
const {
  Builder, By, Key, until,
} = require('selenium-webdriver');

module.exports = async () => {
  this.timeout(30000);
  let driver;
  let vars;

  driver = await new Builder().forBrowser('chrome').build();
  vars = {};

  await driver.get('https://linuxacademy.com/');

  await driver.manage().window().setRect(2026, 1289);
  {
    const element = await driver.findElement(By.linkText('Log In'));
    await driver.actions({ bridge: true }).moveToElement(element).perform();
  }
  await driver.findElement(By.linkText('Log In')).click();
  {
    const element = await driver.findElement(By.CSS_SELECTOR, 'body');
    await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform();
  }
  await driver.findElement(By.css('.auth0-lock-social-button:nth-child(2) > .auth0-lock-social-button-text')).click();
  await driver.findElement(By.linkText('Home')).click();


  await driver.quit();
};
